# Get started with a basic starship configuration
format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "blue bold"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "yellow"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)" 